// Code generated by MockGen. DO NOT EDIT.
// Source: ./request.go
//
// Generated by this command:
//
//	mockgen -source=./request.go -destination=./mocks/request.go
//

// Package mock_odoo is a generated GoMock package.
package mock_odoo

import (
	reflect "reflect"

	pos_odoo "github.com/Nuanu-com/pos-odoo"
	gomock "go.uber.org/mock/gomock"
)

// MockOdooClient is a mock of OdooClient interface.
type MockOdooClient struct {
	ctrl     *gomock.Controller
	recorder *MockOdooClientMockRecorder
	isgomock struct{}
}

// MockOdooClientMockRecorder is the mock recorder for MockOdooClient.
type MockOdooClientMockRecorder struct {
	mock *MockOdooClient
}

// NewMockOdooClient creates a new mock instance.
func NewMockOdooClient(ctrl *gomock.Controller) *MockOdooClient {
	mock := &MockOdooClient{ctrl: ctrl}
	mock.recorder = &MockOdooClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOdooClient) EXPECT() *MockOdooClientMockRecorder {
	return m.recorder
}

// AuthenticatedUserID mocks base method.
func (m *MockOdooClient) AuthenticatedUserID() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthenticatedUserID")
	ret0, _ := ret[0].(int)
	return ret0
}

// AuthenticatedUserID indicates an expected call of AuthenticatedUserID.
func (mr *MockOdooClientMockRecorder) AuthenticatedUserID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthenticatedUserID", reflect.TypeOf((*MockOdooClient)(nil).AuthenticatedUserID))
}

// ClosePOSSession mocks base method.
func (m *MockOdooClient) ClosePOSSession(sessionID int, bankPaymentMethodDiffs []pos_odoo.BankPaymentMethodDiff) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClosePOSSession", sessionID, bankPaymentMethodDiffs)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClosePOSSession indicates an expected call of ClosePOSSession.
func (mr *MockOdooClientMockRecorder) ClosePOSSession(sessionID, bankPaymentMethodDiffs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClosePOSSession", reflect.TypeOf((*MockOdooClient)(nil).ClosePOSSession), sessionID, bankPaymentMethodDiffs)
}

// ComputeAllTax mocks base method.
func (m *MockOdooClient) ComputeAllTax(taxIDs []int, priceUnit, quantity float64) (*pos_odoo.AccountTaxComputeAllResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ComputeAllTax", taxIDs, priceUnit, quantity)
	ret0, _ := ret[0].(*pos_odoo.AccountTaxComputeAllResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ComputeAllTax indicates an expected call of ComputeAllTax.
func (mr *MockOdooClientMockRecorder) ComputeAllTax(taxIDs, priceUnit, quantity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ComputeAllTax", reflect.TypeOf((*MockOdooClient)(nil).ComputeAllTax), taxIDs, priceUnit, quantity)
}

// CreatePOSOrder mocks base method.
func (m *MockOdooClient) CreatePOSOrder(orders []pos_odoo.POSOrderData, draft bool) ([]pos_odoo.POSOrderResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePOSOrder", orders, draft)
	ret0, _ := ret[0].([]pos_odoo.POSOrderResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePOSOrder indicates an expected call of CreatePOSOrder.
func (mr *MockOdooClientMockRecorder) CreatePOSOrder(orders, draft any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePOSOrder", reflect.TypeOf((*MockOdooClient)(nil).CreatePOSOrder), orders, draft)
}

// CreatePOSSession mocks base method.
func (m *MockOdooClient) CreatePOSSession(configID int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePOSSession", configID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePOSSession indicates an expected call of CreatePOSSession.
func (mr *MockOdooClientMockRecorder) CreatePOSSession(configID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePOSSession", reflect.TypeOf((*MockOdooClient)(nil).CreatePOSSession), configID)
}

// CreateProduct mocks base method.
func (m *MockOdooClient) CreateProduct(input pos_odoo.ProductProductInput) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProduct", input)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProduct indicates an expected call of CreateProduct.
func (mr *MockOdooClientMockRecorder) CreateProduct(input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProduct", reflect.TypeOf((*MockOdooClient)(nil).CreateProduct), input)
}

// CreateProductTemplate mocks base method.
func (m *MockOdooClient) CreateProductTemplate(input pos_odoo.ProductTemplateInput) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProductTemplate", input)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProductTemplate indicates an expected call of CreateProductTemplate.
func (mr *MockOdooClientMockRecorder) CreateProductTemplate(input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProductTemplate", reflect.TypeOf((*MockOdooClient)(nil).CreateProductTemplate), input)
}

// PostClosingCashDetails mocks base method.
func (m *MockOdooClient) PostClosingCashDetails(sessionID int, countedCash float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostClosingCashDetails", sessionID, countedCash)
	ret0, _ := ret[0].(error)
	return ret0
}

// PostClosingCashDetails indicates an expected call of PostClosingCashDetails.
func (mr *MockOdooClientMockRecorder) PostClosingCashDetails(sessionID, countedCash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostClosingCashDetails", reflect.TypeOf((*MockOdooClient)(nil).PostClosingCashDetails), sessionID, countedCash)
}

// ReadPOSConfig mocks base method.
func (m *MockOdooClient) ReadPOSConfig(configID int) (*pos_odoo.POSConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadPOSConfig", configID)
	ret0, _ := ret[0].(*pos_odoo.POSConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadPOSConfig indicates an expected call of ReadPOSConfig.
func (mr *MockOdooClientMockRecorder) ReadPOSConfig(configID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadPOSConfig", reflect.TypeOf((*MockOdooClient)(nil).ReadPOSConfig), configID)
}

// ReadPOSSession mocks base method.
func (m *MockOdooClient) ReadPOSSession(sessionID int) (*pos_odoo.POSSessionInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadPOSSession", sessionID)
	ret0, _ := ret[0].(*pos_odoo.POSSessionInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadPOSSession indicates an expected call of ReadPOSSession.
func (mr *MockOdooClientMockRecorder) ReadPOSSession(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadPOSSession", reflect.TypeOf((*MockOdooClient)(nil).ReadPOSSession), sessionID)
}

// ReadProductByID mocks base method.
func (m *MockOdooClient) ReadProductByID(id int, fields []string) (*pos_odoo.ProductProduct, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadProductByID", id, fields)
	ret0, _ := ret[0].(*pos_odoo.ProductProduct)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadProductByID indicates an expected call of ReadProductByID.
func (mr *MockOdooClientMockRecorder) ReadProductByID(id, fields any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadProductByID", reflect.TypeOf((*MockOdooClient)(nil).ReadProductByID), id, fields)
}

// RefundPOSOrder mocks base method.
func (m *MockOdooClient) RefundPOSOrder(orderID int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefundPOSOrder", orderID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefundPOSOrder indicates an expected call of RefundPOSOrder.
func (mr *MockOdooClientMockRecorder) RefundPOSOrder(orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefundPOSOrder", reflect.TypeOf((*MockOdooClient)(nil).RefundPOSOrder), orderID)
}

// SearchReadAccountTax mocks base method.
func (m *MockOdooClient) SearchReadAccountTax(domain []any, fields []string, limit, offset int) (*pos_odoo.SearchReadResult[pos_odoo.AccountTax], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchReadAccountTax", domain, fields, limit, offset)
	ret0, _ := ret[0].(*pos_odoo.SearchReadResult[pos_odoo.AccountTax])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchReadAccountTax indicates an expected call of SearchReadAccountTax.
func (mr *MockOdooClientMockRecorder) SearchReadAccountTax(domain, fields, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchReadAccountTax", reflect.TypeOf((*MockOdooClient)(nil).SearchReadAccountTax), domain, fields, limit, offset)
}

// SearchReadProduct mocks base method.
func (m *MockOdooClient) SearchReadProduct(domain []any, fields []string, limit, offset int) ([]pos_odoo.ProductProduct, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchReadProduct", domain, fields, limit, offset)
	ret0, _ := ret[0].([]pos_odoo.ProductProduct)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchReadProduct indicates an expected call of SearchReadProduct.
func (mr *MockOdooClientMockRecorder) SearchReadProduct(domain, fields, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchReadProduct", reflect.TypeOf((*MockOdooClient)(nil).SearchReadProduct), domain, fields, limit, offset)
}

// SearchReadProductsByTemplateID mocks base method.
func (m *MockOdooClient) SearchReadProductsByTemplateID(templateID int, fields []string) ([]pos_odoo.ProductProduct, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchReadProductsByTemplateID", templateID, fields)
	ret0, _ := ret[0].([]pos_odoo.ProductProduct)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchReadProductsByTemplateID indicates an expected call of SearchReadProductsByTemplateID.
func (mr *MockOdooClientMockRecorder) SearchReadProductsByTemplateID(templateID, fields any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchReadProductsByTemplateID", reflect.TypeOf((*MockOdooClient)(nil).SearchReadProductsByTemplateID), templateID, fields)
}

// TryCashInOut mocks base method.
func (m *MockOdooClient) TryCashInOut(sessionID int, moveType pos_odoo.CashMoveType, amount float64, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TryCashInOut", sessionID, moveType, amount, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// TryCashInOut indicates an expected call of TryCashInOut.
func (mr *MockOdooClientMockRecorder) TryCashInOut(sessionID, moveType, amount, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TryCashInOut", reflect.TypeOf((*MockOdooClient)(nil).TryCashInOut), sessionID, moveType, amount, reason)
}

// UpdateClosingControlStateSession mocks base method.
func (m *MockOdooClient) UpdateClosingControlStateSession(sessionID int, notes string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateClosingControlStateSession", sessionID, notes)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateClosingControlStateSession indicates an expected call of UpdateClosingControlStateSession.
func (mr *MockOdooClientMockRecorder) UpdateClosingControlStateSession(sessionID, notes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateClosingControlStateSession", reflect.TypeOf((*MockOdooClient)(nil).UpdateClosingControlStateSession), sessionID, notes)
}

// WritePOSOrder mocks base method.
func (m *MockOdooClient) WritePOSOrder(ids []int, fields map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WritePOSOrder", ids, fields)
	ret0, _ := ret[0].(error)
	return ret0
}

// WritePOSOrder indicates an expected call of WritePOSOrder.
func (mr *MockOdooClientMockRecorder) WritePOSOrder(ids, fields any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WritePOSOrder", reflect.TypeOf((*MockOdooClient)(nil).WritePOSOrder), ids, fields)
}

// WriteProduct mocks base method.
func (m *MockOdooClient) WriteProduct(ids []int, input pos_odoo.ProductWriteInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteProduct", ids, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteProduct indicates an expected call of WriteProduct.
func (mr *MockOdooClientMockRecorder) WriteProduct(ids, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteProduct", reflect.TypeOf((*MockOdooClient)(nil).WriteProduct), ids, input)
}

// WriteProductTemplate mocks base method.
func (m *MockOdooClient) WriteProductTemplate(ids []int, input pos_odoo.ProductWriteInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteProductTemplate", ids, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteProductTemplate indicates an expected call of WriteProductTemplate.
func (mr *MockOdooClientMockRecorder) WriteProductTemplate(ids, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteProductTemplate", reflect.TypeOf((*MockOdooClient)(nil).WriteProductTemplate), ids, input)
}
